# connect to the default 'podman' network
services:
  eureka-server:
    build: ../roc-eureka-api
    restart: unless-stopped
    container_name: eureka-server
    networks:
      - podman
    ports:
      - "8761:8761"

networks:
  podman:
    driver: bridge